---
# tasks file for mysql_db
- name: Install and Configure Database
  apt: name={{ item }} state=present
  with_items:
    - python-mysqldb
    - mysql-server
    - mysql-client
- name: Start Database Service
  service:
    name: mysql
    state: started
    enabled: yes
- name: Create Database and Users
  mysql_db:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ db_name }}"
    state: present
- name: Create Database User
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'
